quotations/urls.py
# quotations/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('statuses/', views.statusesIndex, name='statusesIndex'),
    path('statuses/add/', views.statusesAdd, name='statusesAdd'),
    path('statuses/edit/<int:id>/', views.statusesEdit, name='statusesEdit'),
    path('statuses/delete/<int:id>/', views.statusesDelete, name='statusesDelete'),
    path('schools/', views.schoolsIndex, name='schoolsIndex'),
    path('schools/add/', views.schoolsAdd, name='schoolsAdd'),
    path('schools/edit/<int:id>/', views.schoolsEdit, name='schoolsEdit'),
    path('schools/delete/<int:id>/', views.schoolsDelete, name='schoolsDelete'),
    path('schools/list/', views.schoolsList, name='schoolsList'),
    path('itadmins/', views.itadminsIndex, name='itadminsIndex'),
    path('itadmins/add/', views.itadminsAdd, name='itadminsAdd'),
    path('itadmins/edit/<int:id>/', views.itadminsEdit, name='itadminsEdit'),
    path('itadmins/delete/<int:id>/', views.itadminsDelete, name='itadminsDelete'),
    path('itadmins/list/', views.itadminsList, name='itadminsList'),
    path('companies/', views.companiesIndex, name='companiesIndex'),
    path('companies/add/', views.companiesAdd, name='companiesAdd'),
    path('companies/edit/<int:id>/', views.companiesEdit, name='companiesEdit'),
    path('companies/delete/<int:id>/', views.companiesDelete, name='companiesDelete'),
    path('technicians/', views.techniciansIndex, name='techniciansIndex'),
    path('technicians/add/', views.techniciansAdd, name='techniciansAdd'),
    path('technicians/edit/<int:id>/', views.techniciansEdit, name='techniciansEdit'),
    path('technicians/delete/<int:id>/', views.techniciansDelete, name='techniciansDelete'),
    path('', views.quotationsIndex, name='quotationsIndex'),
    path('quotations/export/<slug:ids>/', views.quotationsExport, name='quotationsExport'),
    path('quotations/search/', views.quotationsSearch, name='quotationsSearch'),
    path('quotations/add/', views.quotationsAdd, name='quotationsAdd'),
    path('quotations/edit/<int:id>/', views.quotationsEdit, name='quotationsEdit'),
    path('quotations/view/<int:id>/', views.quotationsView, name='quotationsView'),
    path('quotations/delete/<int:id>/', views.quotationsDelete, name='quotationsDelete'),
    path('users/', views.usersIndex, name='usersIndex'),
    path('users/add/', views.usersAdd, name='usersAdd'),
    path('users/edit/<int:id>/', views.usersEdit, name='usersEdit'),
    path('users/view/<int:id>/', views.usersView, name='usersView'),
    path('users/delete/<int:id>/', views.usersDelete, name='usersDelete'),
    path('groups/add/', views.groupsAdd, name='groupsAdd'),
    path('groups/edit/<int:id>/', views.groupsEdit, name='groupsEdit'),
    path('groups/', views.groupsIndex, name='groupsIndex'),
    path('groups/view/<int:id>/', views.groupsView, name='groupsView'),
    path('groups/delete/<int:id>/', views.groupsDelete, name='groupsDelete'),
]

'''path('', views.quotationsIndex, name='quotationsIndex'),
path('add/', views.quotationsAdd, name='quotationsAdd'),
path('edit/<int:id>/', views.quotationsEdit, name='quotationsEdit'),
path('delete/<int:id>/', views.quotationsDelete, name='quotationsDelete'),
path('search/', views.quotationsSearch, name='quotationsSearch'),
path('statuses/search/', views.statusesSearch, name='statusesSearch'),'''

schoolsquotations/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotations.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

quotations/models.py
from django.db import models

class School(models.Model):
	name_en = models.CharField(max_length=100)
	name_ar = models.CharField(max_length=100)
	email = models.EmailField(null=True)

	def __str__(self):
		return self.name_en

class Status(models.Model):
	name = models.CharField(max_length=50)
	color = models.CharField(max_length=7, null=True)

	def __str__(self):
		return self.name

class Company(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(null=True)
	phone = models.CharField(max_length=30, null=True)

	def __str__(self):
		return self.name

class Itadmin(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(null=True)
	phone = models.CharField(max_length=30, null=True)
	school = models.ForeignKey(School, null=True, on_delete=models.SET_NULL)

	def __str__(self):
		return self.name

class Technician(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(null=True)
	phone = models.CharField(max_length=30, null=True)
	department = models.CharField(max_length=100, null=True)

	def __str__(self):
		return self.name


class Quotation(models.Model):
	school = models.ForeignKey(School, null=True, on_delete=models.CASCADE)
	requester = models.IntegerField(null=True)
	itadmin = models.CharField(max_length=100, null=True)
	technician = models.ForeignKey(Technician, null=True, on_delete=models.SET_NULL)
	company = models.ForeignKey(Company, null=True, on_delete=models.SET_NULL)
	status = models.ForeignKey(Status, null=True, on_delete=models.SET_NULL)
	received = models.DateField(null=True)
	notes = models.TextField(null=True)
	created = models.DateField(auto_now_add=True, blank=True)

	def __str__(self):
		return self.notes

quotations/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test

from .forms import StatusForm
from .forms import SchoolForm
from .forms import ItadminForm
from .forms import CompanyForm
from .forms import TechnicianForm
from .forms import QuotationForm
from .forms import SignUpForm
from .forms import EditUserForm
from .forms import GroupForm
from .models import Status
from .models import School
from .models import Itadmin
from .models import Company
from .models import Technician
from .models import Quotation
from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission


import json
import csv
from django.http import HttpResponse

@login_required
def statusesIndex(request):
	statuses_list = Status.objects.all()

	page = request.GET.get('page', 1)

	paginator = Paginator(statuses_list, 10)
	try:
		statuses = paginator.page(page)
	except PageNotAnInteger:
		statuses = paginator.page(1)
	except EmptyPage:
		statuses = paginator.page(paginator.num_pages)

	return render(request,"statuses/index.html",{'statuses':statuses,})

@permission_required('quotations.add_status', raise_exception=True)
def statusesAdd(request):
	form = StatusForm(request.POST or None)
	if form.is_valid():
		form.save()
		return redirect('statusesIndex')
	else:
		return render(request,"statuses/add.html",{'form':form,'action_link': 'statusesAdd','error_message': "There is a problem here."})


@permission_required('quotations.change_status', raise_exception=True)
def statusesEdit(request,id):
	status = Status.objects.get(id=id)
	form = StatusForm(request.POST or None, instance=status)
	if form.is_valid():
		form.save()
		return redirect('statusesIndex')
	else:
		return render(request,"statuses/add.html",{'form':form,'status':status})


@permission_required('quotations.delete_status', raise_exception=True)
def statusesDelete(request,id):
	status = Status.objects.get(id=id)
	status.delete()
	return redirect('statusesIndex')


''' schools functions '''
@login_required
def schoolsIndex(request):
	schools_list = School.objects.all()

	page = request.GET.get('page', 1)

	paginator = Paginator(schools_list, 10)
	try:
		schools = paginator.page(page)
	except PageNotAnInteger:
		schools = paginator.page(1)
	except EmptyPage:
		schools = paginator.page(paginator.num_pages)

	return render(request,"schools/index.html",{'schools':schools,})


def schoolsList(request):
	schools = School.objects.all()
	return render(request,"schools/list.html",{'schools':schools,})


@permission_required('quotations.add_school', raise_exception=True)
def schoolsAdd(request):
	form = SchoolForm(request.POST or None)
	if form.is_valid():
		form.save()
		return redirect('schoolsIndex')
	else:
		return render(request,"schools/add.html",{'form':form,'action_link': 'schoolsAdd','error_message': "There is a problem here."})


@permission_required('quotations.edit_school', raise_exception=True)
def schoolsEdit(request,id):
	school = School.objects.get(id=id)
	form = SchoolForm(request.POST or None, instance=school)
	if form.is_valid():
		form.save()
		return redirect('schoolsIndex')
	else:
		return render(request,"schools/add.html",{'form':form,'school':school})


@permission_required('quotations.delete_school', raise_exception=True)
def schoolsDelete(request,id):
	school = School.objects.get(id=id)
	school.delete()
	return redirect('schoolsIndex')


''' IT Admin '''
@login_required
def itadminsIndex(request):
	itadmins_list = Itadmin.objects.all()

	page = request.GET.get('page', 1)

	paginator = Paginator(itadmins_list, 10)
	try:
		itadmins = paginator.page(page)
	except PageNotAnInteger:
		itadmins = paginator.page(1)
	except EmptyPage:
		itadmins = paginator.page(paginator.num_pages)

	return render(request,"itadmins/index.html",{'itadmins':itadmins,})


@permission_required('quotations.add_itadmin', raise_exception=True)
def itadminsAdd(request):
	form = ItadminForm(request.POST or None)
	if form.is_valid():
		form.save()
		return redirect('itadminsIndex')
	else:
		return render(request,"itadmins/add.html",{'form':form,'action_link': 'itadminsAdd','error_message': "There is a problem here."})

@permission_required('quotations.change_itadmin', raise_exception=True)
def itadminsEdit(request,id):
	itadmin = Itadmin.objects.get(id=id)
	form = ItadminForm(request.POST or None, instance=itadmin)
	if form.is_valid():
		form.save()
		return redirect('itadminsIndex')
	else:
		return render(request,"itadmins/add.html",{'form':form,'itadmin':itadmin})

@permission_required('quotations.delete_itadmin', raise_exception=True)
def itadminsDelete(request,id):
	itadmin = Itadmin.objects.get(id=id)
	itadmin.delete()
	return redirect('itadminsIndex')

def itadminsList(request):
	if request.GET['school_id']:
		#result = result.filter(school__name_en__icontains = request.GET['school_name'])
		itadmins = Itadmin.objects.filter(school__id__icontains = request.GET['school_id'])
		return render(request,"itadmins/list.html",{'itadmins':itadmins,})
	else:
		return render(request,"itadmins/list.html",{'itadmins':itadmins,})



''' Companies '''
@login_required
def companiesIndex(request):
	companies_list = Company.objects.all()

	page = request.GET.get('page', 1)

	paginator = Paginator(companies_list, 10)
	try:
		companies = paginator.page(page)
	except PageNotAnInteger:
		companies = paginator.page(1)
	except EmptyPage:
		companies = paginator.page(paginator.num_pages)

	return render(request,"companies/index.html",{'companies':companies,})


@permission_required('quotations.add_company', raise_exception=True)
def companiesAdd(request):
	form = CompanyForm(request.POST or None)
	if form.is_valid():
		form.save()
		return redirect('companiesIndex')
	else:
		return render(request,"companies/add.html",{'form':form,'action_link': 'companiesAdd','error_message': "There is a problem here."})

@permission_required('quotations.change_company', raise_exception=True)
def companiesEdit(request,id):
	company = Company.objects.get(id=id)
	form = CompanyForm(request.POST or None, instance=company)
	if form.is_valid():
		form.save()
		return redirect('companiesIndex')
	else:
		return render(request,"companies/add.html",{'form':form,'company':company})

@permission_required('quotations.delete_company', raise_exception=True)
def companiesDelete(request,id):
	company = Company.objects.get(id=id)
	company.delete()
	return redirect('companiesIndex')


''' Technicians '''
@login_required
def techniciansIndex(request):
	technicians_list = Technician.objects.all()

	page = request.GET.get('page', 1)

	paginator = Paginator(technicians_list, 10)
	try:
		technicians = paginator.page(page)
	except PageNotAnInteger:
		technicians = paginator.page(1)
	except EmptyPage:
		technicians = paginator.page(paginator.num_pages)

	return render(request,"technicians/index.html",{'technicians':technicians,})


@permission_required('quotations.add_technician', raise_exception=True)
def techniciansAdd(request):
	form = TechnicianForm(request.POST or None)
	if form.is_valid():
		form.save()
		return redirect('techniciansIndex')
	else:
		return render(request,"technicians/add.html",{'form':form,'action_link': 'techniciansAdd','error_message': "There is a problem here."})

@permission_required('quotations.change_technician', raise_exception=True)
def techniciansEdit(request,id):
	technician = Technician.objects.get(id=id)
	form = TechnicianForm(request.POST or None, instance=technician)
	if form.is_valid():
		form.save()
		return redirect('techniciansIndex')
	else:
		return render(request,"technicians/add.html",{'form':form,'technician':technician})

@permission_required('quotations.delete_technician', raise_exception=True)
def techniciansDelete(request,id):
	technician = Technician.objects.get(id=id)
	technician.delete()
	return redirect('techniciansIndex')


''' Quotations '''
@login_required
def quotationsIndex(request):
	statuses_list = Status.objects.only('name')
	technicians_list = Technician.objects.only('name')

	quotations_list = Quotation.objects.all().order_by('-id')

	quotations_ids = []
	for quotation in quotations_list:
		quotations_ids.append(quotation.id)

	quotations_ids_string = '-'.join(str(x) for x in quotations_ids)



	#return HttpResponse(quotations_ids_string)
	page = request.GET.get('page', 1)

	paginator = Paginator(quotations_list, 10)
	try:
		quotations = paginator.page(page)
	except PageNotAnInteger:
		quotations = paginator.page(1)
	except EmptyPage:
		quotations = paginator.page(paginator.num_pages)

	return render(request,"quotations/index.html",{'quotations':quotations,'statuses_list':statuses_list,'technicians_list':technicians_list, 'quotations_ids_string':quotations_ids_string})


def quotationsExport(request,ids):
	ids_array = ids.split('-')
	quotations_list = Quotation.objects.all().filter(id__in = ids_array).order_by('-id')
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition'] = 'attachment; filename="quotationsexport.csv"'

	writer = csv.writer(response)
	writer.writerow(['Id', 'School','requester', 'Technician', 'Company', 'Status', 'Received', ' Created'])

	for quotation in quotations_list:
		row = []
		row.append('QS'+str(quotation.id))
		row.append(quotation.school)
		row.append(quotation.technician)
		row.append(quotation.company)
		row.append(quotation.status)
		row.append(quotation.received)
		row.append(quotation.created)
		writer.writerow(row)


quotations/templates/quotations/index.html
{% extends "quotations/base.html" %}
{% load static %}

{% block content %}






<div class="panel panel-primary panel-custom-primary">

	<div class="panel-heading">
		<h4>Search</h4>
	</div>

	<div class="panel-body">
		<div class="row">
			<div class="col-md-4">
				<div class="input-group input search_form">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"></span>
					<input name="search_id" type="text" class="form-control" placeholder="Id" id="search_id">
				</div>
			</div>
			<div class="col-md-4">
				<div class="input-group input search_form">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"></span>
					<input name="search_school_name" type="text" class="form-control" placeholder="School Name" id="search_school_name">
				</div>
			</div>
			<div class="col-md-4">
				<div class="input-group input search_form">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"></span>
					<input name="search_company_name" type="text" class="form-control" placeholder="Company Name" id="search_company_name">
				</div>
			</div>
		</div>

			<br />
		<div class="row">
			<div class="col-md-6">
				<div class="input-group input search_form">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"></span>
					<!--<input name="search_technician_name" type="text" class="form-control" placeholder="Technician Name" id="search_technician_name">-->
					<select name="search_technician_name" class="form-control" placeholder="Technician" id="search_technician_name">
						<option value="">Technician</option>
						{% for technician in technicians_list %}
							<option value="{{technician}}">{{technician}}</option>
						{% endfor %}
					</select>
				</div>
			</div>


			<div class="col-md-6">
				<div class="input-group input search_form">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"></span>
					<!--<input name="search_status_name" type="text" class="form-control" placeholder="Status" id="search_status_name">-->
					<select name="search_status_name" class="form-control" placeholder="Status" id="search_status_name">
						<option value="">Status</option>
						{% for status in statuses_list %}
							<option value="{{status}}">{{status}}</option>
						{% endfor %}
					</select>
				</div>
			</div>
	
		</div>

		<br />

		<!--<div class="row">
			<div class="col-md-4 col-md-offset-1">
				<div class="input-group input search_form">
					<input name="search_created_from" type="text" class="form-control" placeholder="Created > From" id="search_created_from">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"><span class="glyphicon glyphicon-calendar"></span></span>
				</div>
			</div>


			<div class="col-md-4 col-md-offset-1">
				<div class="input-group input search_form">
					<input name="search_created_to" type="text" class="form-control" placeholder="Created > To" id="search_created_to">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"><span class="glyphicon glyphicon-calendar"></span></span>
				</div>
			</div>
	
		</div>

		<br />-->

		<div class="row">
			<div class="col-md-4 col-md-offset-1">
				<div class="input-group input search_form">
					<input name="search_received_from" type="text" class="form-control" placeholder="Received > From" id="search_received_from">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"><span class="glyphicon glyphicon-calendar"></span></span>
				</div>
			</div>


			<div class="col-md-4 col-md-offset-1">
				<div class="input-group input search_form">
					<input name="search_received_to" type="text" class="form-control" placeholder="Received > To" id="search_received_to">
					<span class="input-group-addon input-group-addon-custom" id="sizing-addon2"><span class="glyphicon glyphicon-calendar"></span></span>
				</div>
			</div>
	
		</div>
	</div>
</div>







<div class="panel panel-default manage_container panel-custom-primary">

	<div class="fixed-buttons">
		{% if perms.quotations.add_quotation %}

			<a href="{% url 'quotationsAdd' %}" class="btn-circle btn-add" title="" data-toggle="tooltip" data-original-title="Add Quotation">
				<!--<img src="{% static 'quotations/img/add-button.png' %}" alt="">-->
				<span class="glyphicon glyphicon-plus icons-style-inverse"></span>
			</a>
		{% endif %}


		{% if quotations_ids_string %}
			<a href="{% url 'quotationsExport' quotations_ids_string %}" class="btn-circle btn-export" title="" data-toggle="tooltip" data-original-title="Export">
					<!--<img src="{% static 'quotations/img/add-button.png' %}" alt="">-->
					<span class="glyphicon glyphicon-export icons-style-inverse"></span>
			</a>
		{% endif %}

	</div>

	<div class="panel-heading">
		<h4>Quotations</h4>
	</div>

	<div class="panel-body">
		<table class="table-responsive table_custom_manage">
			<thead>
				<tr>
					<th>Id</th>
					<th>School</th>
					<th>Requester</th>
					<th>Assigned To</th>
					<th>Company</th>
					<th>Status</th>
					<th>Received</th>
					<th>Created</th>
				</tr>
			</thead>
			<tbody>
					{% if quotations %}
					    {% for quotation in quotations %}
					    <tr>
					    	<td>QS{{quotation.id}}</td>
					        <td>{{quotation.school}}</td>
					        <td>
					        	{% if quotation.requester == 1 %}
					        		School
					        	{% elif quotation.requester == 2 %}
					        		{{quotation.itadmin}}
					        	{% endif %}
					        </td>
					        <td>{{quotation.technician}}</td>
					        <td>{{quotation.company}}</td>
					        <td>
					        	<span class="coloured-circle" style="background-color: {{quotation.status.color}};"></span>
					        	<span>{{quotation.status}}</span>
					        </td>
					        <td>{{quotation.received|date:"M d, Y"}}</td>
					        <td>{{quotation.created|date:"M d, Y"}}</td>
					        <td><a href="{% url 'quotationsView' quotation.id %}" class="manage_icons details_icon" title="" data-toggle="tooltip" data-html="true" data-original-title="{{quotation.notes|linebreaks}}<br />Click for more details"><span class="glyphicon glyphicon-list-alt icons-style"></span></a></td>
					        {% if perms.quotations.change_quotation %}
					        	<td><a href="{% url 'quotationsEdit' quotation.id %}" class="manage_icons edit_icon" title="" data-toggle="tooltip" data-original-title="Edit"><span class="glyphicon glyphicon-edit icons-style"></span></a></td>
					        {% endif %}
					        {% if perms.quotations.delete_quotation %}
					        	<td><a href="{% url 'quotationsDelete' quotation.id %}" class="manage_icons delete_icon" title="" data-toggle="tooltip" data-original-title="Delete"><span class="glyphicon glyphicon-trash icons-style"></span></a></td>
					        {% endif %}
					    </tr>
					    {% endfor %}
					{% else %}
					    <p>There is no Quotations available</p>
					{% endif %}
					
				
			</tbody>
		</table>

		{% if quotations.has_other_pages %}
			<ul class="pagination">
			    {% if quotations.has_previous %}
			     	<li><a href="?page={{ quotations.previous_page_number }}">&laquo;</a></li>
			    {% else %}
			     	<li class="disabled"><span>&laquo;</span></li>
			    {% endif %}
			    {% for i in quotations.paginator.page_range %}
			    	{% if quotations.number == i %}
			    		<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
			    	{% else %}
			    		<li><a href="?page={{ i }}">{{ i }}</a></li>
			    	{% endif %}
			    {% endfor %}
			    {% if quotations.has_next %}
			    	<li><a href="?page={{ quotations.next_page_number }}">&raquo;</a></li>
			    {% else %}
			    	<li class="disabled"><span>&raquo;</span></li>
			    {% endif %}
			</ul>
		{% endif %}


		
	</div>

</div>











<script type="text/javascript">
	//var base_directory = "<?php echo $this->webroot; ?>";
	
	//alert(query);
	var  in_action = false;
	if(in_action == false) {
		$('.search_form').keyup(function() {
			in_action = true;
			search_function();
			
		});

		$('.search_form').change(function() {
			in_action = true;
			search_function();
			
		});
	}




	function search_function() {
		var query = {
			'id' : $('#search_id').val(),
			'school_name' : $('#search_school_name').val(),
			'company_name' : $('#search_company_name').val(),
			'technician_name' : $('#search_technician_name').val(),
			'status_name' : $('#search_status_name').val(),
			'received_from' : $('#search_received_from').val(),
			'received_to' : $('#search_received_to').val(),
		};

		//alert(JSON.stringify(query));
		$.ajax({
		  	type: 'GET',
			url: "{% url 'quotationsSearch' %}",
			data: query,
		    beforeSend: function() {
		    	//$('.scout_confirm_message').html('');
		    },
		    success: function(data) {
				$('.manage_container').html("");
				$('.manage_container').html(data);
				in_action = false;
				//alert(data);
				$('[data-toggle="tooltip"]').tooltip();
		    },
			error: function(e){
				alert(e.status);
			}
		});
	}
	
</script>


<script type='text/javascript'>
	function confirm_delete(message) {
			$(document).ready(function() {
				$('.delete_icon').click(function() {
					if(confirm(message)) {

					} else {
						return false;
					}
				});	
			});
	}
	confirm_delete('Are you sure you want to delete this quotation ?');
</script>



{% endblock %}


quotations/templates/quotations/view.html
{% extends "quotations/base.html" %}
{% load static %}

{% block content %}


<div class="fixed-buttons">

	{% if perms.quotations.change_quotation %}
			<a href="{% url 'quotationsEdit' quotation.id %}" class="btn-circle btn-edit" title="" data-toggle="tooltip" data-original-title="Edit"><span class="glyphicon glyphicon-edit icons-style-inverse"></span></a>
		
	{% endif %}

</div>

<div class="panel panel-primary panel-custom-primary">
	<div class="panel-heading">
		Quotation #{{quotation.id}}
	</div>
	<div class="panel-body">
		<table class="table">
			<tbody>
				<tr>
					<th>School</th>
					<td>{{quotation.school}}</td>
				</tr>
				<tr>
					<th>Requester</th>
					<td>
					    {% if quotation.requester == 1 %}
					        School
					    {% elif quotation.requester == 2 %}
					        IT Admin
					    {% endif %}
					</td>
				</tr>
				<tr>
					<th>Technician</th>
					<td>{{quotation.technician}}</td>
				</tr>
				<tr>
					<th>Company</th>
					<td>{{quotation.company}}</td>
				</tr>
				<tr>
					<th>Received</th>
					<td>{{quotation.received}}</td>
				</tr>
				<tr>
					<th>Created</th>
					<td>{{quotation.created}}</td>
				</tr>
				<tr>
					<th>Notes</th>
					<td>{{quotation.notes}}</td>
				</tr>
				<tr>
					<th>Status</th>
					<td>
						<span class="coloured-circle" style="background-color: {{quotation.status.color}};"></span>
					    <span>{{quotation.status}}</span>
					</td>
				</tr>
				
			</tbody>
		</table>
	</div>
</div>





{% endblock %}
